# Generated by Django 2.2.17 on 2020-12-07 08:52

import json

from pathlib import Path

from django.conf import settings
from django.db import migrations, models


def add_values(apps, schema_editor):
    path = Path(settings.BASE_DIR + "/values_principles/fixtures/values.json")
    with path.open() as data_file:
        json_file = json.load(data_file)
    Value = apps.get_model("values_principles", "Value")
    for data in json_file:
        title = data.get("fields").get("title")
        description = data.get("fields").get("description")
        Value.objects.create(title=title, description=description)


def add_principles(apps, schema_editor):
    path = Path(settings.BASE_DIR + "/values_principles/fixtures/principles.json")
    with path.open() as data_file:
        json_file = json.load(data_file)
    Principle = apps.get_model("values_principles", "Principle")
    for data in json_file:
        title = data.get("fields").get("title")
        description = data.get("fields").get("description")
        Principle.objects.create(title=title, description=description)


class Migration(migrations.Migration):

    dependencies = [
        ("values_principles", "0003_auto_20210817_0209"),
    ]

    operations = [
        migrations.RunPython(add_values, migrations.RunPython.noop),
        migrations.RunPython(add_principles, migrations.RunPython.noop),
    ]
